language: php

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: setup=lowest
      dist: precise
    - php: 5.4
      env: setup=lowest
    - php: 5.5
      env: setup=lowest
    - php: 5.6
      env: setup=lowest
    - php: 7.0
      env: setup=lowest
    - php: 7.1
      env: setup=lowest
    - php: 7.1
    - php: 7.2
      env: setup=lowest
    - php: 7.2
    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: coverage=on
    - php: 7.3
      env: multitest=on

before_install:
  - travis_retry composer self-update

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --dev; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --dev; fi

script:
  - if [[ $multitest = 'off' ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=clover.xml; fi
  - if [[ $multitest = 'on' ]]; then vendor/bin/multi-tester --verbose; fi

after_script:
  - if [[ $coverage = 'on' ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  - if [[ $coverage = 'on' ]]; then bash <(curl -s https://codecov.io/bash); fi

env:
  global:
    - setup=stable
    - coverage=off
    - multitest=off
    - CC_TEST_REPORTER_ID=445bfa02f795c64b7cfe96c610d906b46a7b889acc965139c990184238742909
